<h2>Últimas entradas</h2>
<?php if(isset($this->posts) && count($this->posts)):?>
<table>
    <?php for($i = 0; $i < count($this->posts); $i++):?>
    <tr>
        <!-- dentro del for se van a recorrer los elementos que devuelva
        el controlador a través del arreglo en el método getPosts() que se 
        está accediendo con _view->posts --!>
        <td><?php echo $this->posts[$i]['id'];?></td>
        <td><?php echo $this->posts[$i]['titulo'];?></td>
        <td><?php echo $this->posts[$i]['cuerpo'];?></td>
        <?php  if(Session::accesosView('especial')): ?>
        <td><a href="<?php echo BASE_URL . 'post/editar/'. $this->posts[$i]['id']; ?>">Editar</a></td>
        <td><a href="<?php echo BASE_URL . 'post/eliminar/'. $this->posts[$i]['id']; ?>">Eliminar</a></td>
        <?php  endif;?>
    </tr>
    <?php endfor;?>
</table>
<?php else:?>
<p><strong>No hay nada para mostrar.</strong></p>
<?php endif;?>

<?php if(Session::accesoViewEstricto(array('usuario'))): ?>
<p><a href="<?php BASE_URL; ?>post/nuevo">Agregar entrada</a></p>
<?php endif;?>
        
        