<?php // if(isset($this->prueba)) echo $this->prueba?>
<form id="form1" method="POST" action="<?php echo BASE_URL?>post/nuevo">
    <!-- el valor guardar es la variable de control del formulario -->
    <input hidden="hidden" name="guardar" value="1" />
    <p>Titulo: <br/>
        <input type="text" name="titulo" value="<?php if(isset($this->datos['titulo'])) echo $this->datos['titulo'] ?>"/>
    </p>
    <p>Cuerpo: <br/>
        <textarea type="text" name="cuerpo"><?php if(isset($this->datos['cuerpo'])) echo $this->datos['cuerpo'] ?></textarea>
    </p>
    <input type="submit" class="button" value="Guardar" />
</form>